### ISSUE TITLE
Create Basic CI for the project

### ISSUE THREAD

**Issue by vcwild** [brdevstreamers/brdevstreamers-api#17]
Desenvolver um CI usando o GH actions que rode apenas um linter básico.
Develop a CI using GH actions that runs basic linting

Requirements:

- Tabulation with 100 cols
- Do not enforce double quotes

**Comment by RishiKumarRay** [comment]
@flaviojmendes can you elaborate this?

**Comment by vcwild** [comment]
There is already a PR for this. Please review
