### ISSUE TITLE
Choose a single version of Python

### ISSUE THREAD

**Issue by rn4n** [brdevstreamers/brdevstreamers-api#24]
The python versions defined in the dependency management file and dockerfile are different.

https://github.com/Br-Dev-Streamers/brdevstreamers/blob/548225f0110940ba4517f35ef92d9589945b0878/Dockerfile#L1
https://github.com/Br-Dev-Streamers/brdevstreamers/blob/548225f0110940ba4517f35ef92d9589945b0878/Pipfile#L65

The purpose of this issue is to specify one and only one version of Python to be adopted in the project.

Maybe the latest? [**3.10**](https://www.python.org/downloads/release/python-3102/)

**Comment by vcwild** [comment]
3.10 is probably too bleeding edge for now, maybe in 6 months. I vouch for using Python 3.9
